### ISSUE TITLE
Differences with old release

### ISSUE THREAD

**Issue by FloRS13** [HPDE-Tools/CANMIM#2]
Hi,

First, huge thanks for making public your work :)

What's the main improvement hard and software between this version and the older publish directly on your profile @zeroomega ?

My idea is to use parts of your work to make a CANbus analog input extension for my MaxxECU standalone ECU on my old '91 Nissan 200SX RS13 (240SX in the US) :)

**Comment by zeroomega** [comment]
The old repo is for a EPS32C3 based board and the board has 2 variants. One has 2 CANbus (ESP32C3 has one and the board has a MicroChip MCP2515/25625 CAN controller). 2 CANbus allow analog CAN data to be isolated from car's can bus to avoid any ECU faults. The other variant only has 1 CAN bus, which injects analog data directly to car's can bus. A few people in 86DriveChallenge used the 2nd variant.

But ESP32C6 natively has 2 CAN controllers, in this case it is easier to build a board without using a dedicated can controller. The old repo isn't designed in a way that is easy to be refactored to support the C6 MCU, so I rewrite the software and put it here.

**Comment by FloRS13** [comment]
Thank you for your answer :)
